export enum EnvKey {
  NodeEnv = 'NODE_ENV',
  Port = 'APP_PORT',
  HashSalt = 'HASH_SALT',
  JwtAccessSecret = 'JWT_ACCESS_SECRET',
  JwtRefreshSecret = 'JWT_REFRESH_SECRET',
  JwtAccessExpiresIn = 'JWT_ACCESS_EXPIRES_IN',
  JwtRefreshExpiresIn = 'JWT_REFRESH_EXPIRES_IN',
  DatabaseHost = 'DB_HOST',
  DatabasePort = 'DB_PORT',
  DatabaseUsername = 'DB_USERNAME',
  DatabasePassword = 'DB_PASSWORD',
  DatabaseName = 'DB_NAME',
  DatabaseSynchronize = 'DB_SYNCHRONIZE',
  LoggerType = 'LOGGER_TYPE',
  S3Region = 'S3_REGION',
  S3AccessKeyId = 'S3_ACCESS_KEY_ID',
  S3SecretAccessKey = 'S3_SECRET_ACCESS_KEY',
  S3Endpoint = 'S3_ENDPOINT',
  S3Bucket = 'S3_BUCKET_NAME',
  CorsOrigins = 'CORS_ORIGINS',
  ThrottleTtl = 'THROTTLE_TTL',
  ThrottleLimit = 'THROTTLE_LIMIT',
}
